### ISSUE TITLE
Add new `kwctl scaffold artifacthub-pkg` command

### ISSUE THREAD

**Issue by viccuad** [kubewarden/kwctl#418]
Relates to 

As specified in https://github.com/kubewarden/rfc/pull/15, add a new `kwctl scaffold artifacthub-pkg` that generates an `artifacthub-pkg.yml` for a given policy.

## Acceptance criteria

- Do this by implementing a serializable `ArtifacthubPkg{}` struct that matches [artifacthub-pkg.yml](https://togithub.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml). It doesn't need to implement all fields, only the ones we cover. Double check with the ones already written by hand to see we aren't missing any derivable info from metadata.yml. As an example: [verify-image-signatures/blob/main/artifacthub-pkg.yml](https://github.com/kubewarden/verify-image-signatures/blob/main/artifacthub-pkg.yml) 
- Provide a `TryFrom()` from `Metadata{}` for `ArtifacthubPkg{}`, that derives and checks the fields according to the RFC.
- Add a new `kwctl scaffold artifacthub-pkg --version v0.0.0 --usage Usage.md --metadata-path metadata.yml`. This command will print the resulting `artifacthub-pkg.yml`, failing according to the TryFrom definitions in the RFC.
- Provide tests

**Comment by flavio** [comment]
The `scaffold artifacthub` command should also have a cli flag that points to the `questions.yml` file.

I also think the `scaffold artifacthub` should not have a `usage` flag, that's because the policy usage instructions are not part of the `artifacthub-pkg.yml`.

To recap, this is what I would propose as flags of the `scaffold artifacthub` command:

* `--questions-ui QUESTIONS`: mandatory, this will read the contents of the question file
* `--version VERSION`: mandatory

About the `--version` flag. I would start with a mandatory version, next we can make it optional and have the code figure out what is the version of a Rust policy by looking at the contents of the `Cargo.toml`. With other types of policies (like Go, Rego,...) the lack of this flag would lead to an error
