### ISSUE TITLE
Pushing to an artifactory OCI registry results in 406 Not Acceptable

### ISSUE THREAD

**Issue by lsoica** [kubewarden/kwctl#59]
Although Artifactory is OCI compliant, https://www.jfrog.com/confluence/display/JFROG/Docker+Registry, following the official docs for distributing policies (https://docs.kubewarden.io/distributing-policies.html) results in:
```
kwctl push annotated-policy.wasm registry://<registry fqdn>/palindromify-policy:v0.0.1
Error: could not push policy: could not push policy: An unexpected error occured: code=406 Not Acceptable, message='{
  "errors" : [ {
    "status" : 406,
    "message" : "Not Acceptable"
  } ]
}'
```

How can I troubleshoot further?

LE: Using the same registry with ORAS, works as expected https://github.com/oras-project/oras
```
oras push  <registry fqdn>/palindromify-policy:v0.0.1 --manifest-config "config.json:application/vnd.wasm.config.v1+json" ./annotated-policy.wasm:application/vnd.wasm.content.layer.v1+wasm
Uploading 1e0afe56fa4e annotated-policy.wasm
Pushed <registry fqdn>/palindromify-policy:v0.0.1
Digest: sha256:<sha>
```
Then, applying the policy works as expected.

**Comment by ereslibre** [comment]
Thank you @lsoica for the report. `kwctl` uses the [`oci-distribution` crate](https://github.com/krustlet/krustlet/tree/main/crates/oci-distribution) from the `krustlet` project for pushing OCI artifacts to registries.

It's very possible that the problematic logic happens inside this crate when pushing, but I didn't confirm it yet.

**Comment by flavio** [comment]
@ereslibre I have an instance of artifactory running in their free tier, I can reproduce the issue.

**Comment by ereslibre** [comment]
> @ereslibre I have an instance of artifactory running in their free tier, I can reproduce the issue.

Thanks for confirming, I will look into this.

**Comment by ereslibre** [comment]
It took a bit of speleology but the problem boils down to the `Accept` header not being sent when pushing the configuration and the layers. The request is being created on the `oci-distribution` crate.

Looking at the description on the distribution spec and I think JFrog is having some behavior that is not strictly defined in the spec: https://github.com/opencontainers/distribution-spec/blob/main/spec.md.

On the pulling manifest specification, it is described that the client [should include an `Accept` header](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests). However, on the [pushing description](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#push), there is no such requirement.

I'm going to ping this issue with the path forward in order to fix the problem

**Comment by ereslibre** [comment]
https://github.com/kubewarden/krustlet/compare/oci-distribution-fix-push-to-ghcr...kubewarden:oci-distribution-fix-push-to-jfrog passes through the 406 problem, but then the `Location` header the server should set is not properly detected. This is a different problem and will be tackled here as well.

**Comment by ereslibre** [comment]
Related:

- https://github.com/opencontainers/distribution-spec/issues/212#issue-741619000 (section "3.2. "Proactive Negotiation" rfc7231, section 3.4.1")
- https://www.jfrog.com/jira/browse/RTFACT-25069

**Comment by ereslibre** [comment]
I have opened https://github.com/krustlet/krustlet/pull/670 fixing the relevant issues on the `oci-distribution` plate.

However, JFrog is not following the spec as expected as described in https://github.com/krustlet/krustlet/pull/670#issue-718766231. I'm reporting that to the JFrog team and reporting back here.

**Comment by ereslibre** [comment]
Despite I contacted JFrog one month ago regarding this issue I had no response from them. If https://github.com/krustlet/krustlet/pull/670 gets merged, I would call this issue done from our side.
