### ISSUE TITLE
Ensure SLSA Lvl 3 in kwctl

### ISSUE THREAD

**Issue by jvanz** [kubewarden/kwctl#933]
Ensure SLSA Lvl 3 as specified in https://github.com/kubewarden/kubewarden-controller/issues/856.

**Comment by jvanz** [comment]
I'm closing this because we are focusing on enabling SLSA Lvl 3 in container images. kwctl does not produce images. Thus, closing this for now.

**Comment by viccuad** [comment]
Gave a try to this with https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md.
It turned out quite difficult, since as it is a reusable workflow and one cannot nest them, one needs to do the usual of passing inputs and ouputs back and forth.
For documenting purposes, here's the approach:
https://github.com/kubewarden/kwctl/compare/main...viccuad:kwctl:slsa
https://github.com/viccuad/kwctl/actions/runs/11292290557

**Comment by viccuad** [comment]
A simpler try, in progress, this time with https://github.com/actions/attest-build-provenance.
See: https://github.com/kubewarden/kwctl/compare/main...viccuad:kwctl:slsa-gh
